import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#fdfcff',
        'surface-container': '#ffe9e5',
        'on-secondary-fixed': '#061f1e',
        'tertiary-container': '#0079c5',
        'primary-fixed-dim': '#ffb4a4',
        'secondary-fixed': '#cde8e6',
        'on-surface': '#281713',
        'primary-fixed': '#ffdad3',
        surface: '#fff8f6',
        'surface-container-highest': '#fcdbd4',
        'surface-tint': '#b72300',
        'on-tertiary-fixed-variant': '#00497b',
        'inverse-primary': '#ffb4a4',
        'outline-variant': '#e6bdb4',
        'on-primary-fixed': '#3d0600',
        'primary-container': '#df2e02',
        tertiary: '#005f9d',
        'surface-variant': '#fcdbd4',
        'surface-dim': '#f3d3cc',
        'on-tertiary-fixed': '#001d35',
        'tertiary-fixed-dim': '#9ccaff',
        'secondary-container': '#cde8e6',
        'error-container': '#ffdad6',
        secondary: '#4b6361',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#516967',
        'secondary-fixed-dim': '#b2ccca',
        'on-surface-variant': '#5d4039',
        'on-secondary-fixed-variant': '#334b4a',
        'inverse-on-surface': '#ffede9',
        'on-primary-fixed-variant': '#8c1800',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        primary: '#b32200',
        'surface-container-lowest': '#ffffff',
        outline: '#916f67',
        'surface-container-low': '#fff0ed',
        'on-background': '#281713',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        'surface-bright': '#fff8f6',
        'tertiary-fixed': '#d0e4ff',
        'surface-container-high': '#ffe2dc',
        'inverse-surface': '#3f2c27',
        background: '#fff8f6',
        'on-primary-container': '#fffbff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '20px',
        'container-max': '1280px',
        'margin-desktop': '40px',
        unit: '8px',
        'gutter-desktop': '24px',
        'gutter-mobile': '16px',
      },
      fontFamily: {
        'body-md': ['"Helvetica, Arial, sans-serif"'],
        'headline-lg': ['"Helvetica, Arial, sans-serif"'],
        'label-sm': ['"Helvetica, Arial, sans-serif"'],
        'label-md': ['"Helvetica, Arial, sans-serif"'],
        'headline-xl': ['"Helvetica, Arial, sans-serif"'],
        'headline-lg-mobile': ['"Helvetica, Arial, sans-serif"'],
        'body-lg': ['"Helvetica, Arial, sans-serif"'],
        'headline-md': ['"Helvetica, Arial, sans-serif"'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
} satisfies Config;
